# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-30 07:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flower',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flower_id', models.BigIntegerField()),
                ('description', models.CharField(max_length=200)),
                ('foto_linl', models.CharField(max_length=200)),
            ],
        ),
    ]
